<?php

/**
 * @file
 * This will creatre aa from.
 */

/**
 * This is example module.
 */
function form_example_menu() {
  $items = array();

  // This creates a URL that will call this form at "examples/form-example".
  $items['examples/form-example'] = array(
  // Page title.
    'title' => 'Example Form',
    'description' => 'A form to mess around with.',
  // This is the function that will be called when the
  // page is accessed.  for a form, use drupal_get_form.
    'page callback' => 'drupal_get_form',
  // Put the name of the form here.
    'page arguments' => array('form_example_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * From example.
 */
function form_example_form($form, &$form_state) {

  $form['price'] = array(
  // You can find a list of available types in the form api.
    '#type' => 'textfield',
    '#title' => 'What is Your Price?',
    '#size' => 10,
    '#maxlength' => 10,
  // Make this field required.
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );

  return $form;
}

/**
 * From validate example.
 */
function form_example_form_validate($form, &$form_state) {
  if (!($form_state['values']['price'] > 0)) {
    form_set_error('price', t('Price must be a positive number.'));
  }
}

/**
 * Form submit example.
 */
function form_example_form_submit($form, &$form_state) {
}
